Repository COW-dev/eat-da-be, pull requests merged in 2023-10, with the labels that each got.

#25 [feature] storehours domain 정의 및 테스트 작성
  build.gradle.kts
  src/main/kotlin/com/mjucow/eatda/common/vo/DayOfWeek.kt
  src/main/kotlin/com/mjucow/eatda/domain/store/entity/Store.kt
  src/main/kotlin/com/mjucow/eatda/domain/store/entity/StoreHours.kt
  src/main/resources/db/changelog/230929-store_hours.sql
  src/test/kotlin/com/mjucow/eatda/domain/store/entity/StoreHoursTest.kt
  src/test/kotlin/com/mjucow/eatda/domain/store/entity/StoreTest.kt
  src/test/kotlin/com/mjucow/eatda/domain/store/entity/objectmother/EntityMother.kt
  src/test/kotlin/com/mjucow/eatda/domain/store/entity/objectmother/ObjectMother.kt
  src/test/kotlin/com/mjucow/eatda/domain/store/entity/objectmother/StoreHoursMother.kt
  src/test/kotlin/com/mjucow/eatda/domain/store/entity/objectmother/StoreMother.kt
Labels: feature, size/XL

#26 [feature] store application 구현
  build.gradle.kts
  src/main/kotlin/com/mjucow/eatda/common/config/JacksonConfiguration.kt
  src/main/kotlin/com/mjucow/eatda/common/vo/PhoneNumber.kt
  src/main/kotlin/com/mjucow/eatda/common/vo/deseializer/PhoneNumberDeserializer.kt
  src/main/kotlin/com/mjucow/eatda/domain/store/service/command/CategoryCommandService.kt
  src/main/kotlin/com/mjucow/eatda/domain/store/service/command/StoreCommandService.kt
  src/main/kotlin/com/mjucow/eatda/domain/store/service/command/dto/StoreCreateCommand.kt
  src/main/kotlin/com/mjucow/eatda/domain/store/service/command/dto/StoreUpdateCommand.kt
  src/main/kotlin/com/mjucow/eatda/domain/store/service/query/CategoryQueryService.kt
  src/main/kotlin/com/mjucow/eatda/domain/store/service/query/StoreQueryService.kt
  src/main/kotlin/com/mjucow/eatda/domain/store/service/query/dto/StoreDetailDto.kt
  src/main/kotlin/com/mjucow/eatda/domain/store/service/query/dto/StoreDto.kt
  src/main/kotlin/com/mjucow/eatda/domain/store/service/query/dto/StoreHoursDto.kt
  src/main/kotlin/com/mjucow/eatda/domain/store/service/query/dto/StoreHoursList.kt
  src/main/kotlin/com/mjucow/eatda/persistence/store/StoreRepository.kt
  src/test/kotlin/com/mjucow/eatda/common/objectmother/EntityMother.kt
  src/test/kotlin/com/mjucow/eatda/common/objectmother/ObjectMother.kt
  src/test/kotlin/com/mjucow/eatda/domain/store/entity/objectmother/StoreHoursMother.kt
  src/test/kotlin/com/mjucow/eatda/domain/store/entity/objectmother/StoreMother.kt
  src/test/kotlin/com/mjucow/eatda/domain/store/service/command/StoreCommandServiceDataTest.kt
  src/test/kotlin/com/mjucow/eatda/domain/store/service/query/StoreQueryServiceDataTest.kt
Labels: feature, size/XL

#27 [feature] store api 구현 및 테스트 작성
  src/main/kotlin/com/mjucow/eatda/domain/store/service/query/StoreQueryService.kt
  src/main/kotlin/com/mjucow/eatda/domain/store/service/query/dto/StoreDetailDto.kt
  src/main/kotlin/com/mjucow/eatda/persistence/store/StoreRepository.kt
  src/main/kotlin/com/mjucow/eatda/presentation/store/StoreController.kt
  src/main/resources/static/swagger-ui/openapi3.yaml
  src/test/kotlin/com/mjucow/eatda/domain/store/service/query/StoreQueryServiceDataTest.kt
  src/test/kotlin/com/mjucow/eatda/presentation/AbstractMockMvcTest.kt
  src/test/kotlin/com/mjucow/eatda/presentation/store/StoreControllerMvcTest.kt
  src/test/kotlin/com/mjucow/eatda/presentation/store/category/CategoryMvcTest.kt
Labels: feature, size/XL

#28 [feature] JOOQ 기반 카테고리 가게 커서 조회
  build.gradle.kts
  gradle.properties
  settings.gradle.kts
  src/main/kotlin/com/mjucow/eatda/common/config/JacksonConfiguration.kt
  src/main/kotlin/com/mjucow/eatda/common/config/JooqContextConfiguration.kt
  src/main/kotlin/com/mjucow/eatda/common/config/JooqToSpringExceptionTransformer.kt
  src/main/kotlin/com/mjucow/eatda/domain/store/service/query/StoreQueryService.kt
  src/main/kotlin/com/mjucow/eatda/persistence/store/StoreCustomRepository.kt
  src/main/kotlin/com/mjucow/eatda/persistence/store/StoreCustomRepositoryImpl.kt
  src/main/kotlin/com/mjucow/eatda/persistence/store/StoreRepository.kt
  src/main/kotlin/com/mjucow/eatda/presentation/store/StoreController.kt
  src/main/resources/application.yml
  src/main/resources/db/changelog/231006-add_store_cateogry_index.sql
  src/test/kotlin/com/mjucow/eatda/domain/AbstractDataTest.kt
  src/test/kotlin/com/mjucow/eatda/domain/store/service/query/StoreQueryServiceDataTest.kt
  src/test/kotlin/com/mjucow/eatda/persistence/store/StoreCustomRepositoryImplTest.kt
  src/test/kotlin/com/mjucow/eatda/presentation/store/StoreControllerMvcTest.kt
  src/test/resources/logback-test.xml
Labels: feature, size/XL

#29 [feature] menu 도메인 정의 및 테스트 작성
  src/main/kotlin/com/mjucow/eatda/domain/store/entity/Menu.kt
  src/main/resources/db/changelog/231014-menu.sql
  src/test/kotlin/com/mjucow/eatda/domain/store/entity/MenuTest.kt
  src/test/kotlin/com/mjucow/eatda/domain/store/entity/objectmother/MenuMother.kt
Labels: feature, size/L

#16 [feature] notice 관련 기능 구현
  src/main/kotlin/com/mjucow/eatda/domain/notice/entity/Notice.kt
  src/main/kotlin/com/mjucow/eatda/domain/notice/service/command/NoticeCommandService.kt
  src/main/kotlin/com/mjucow/eatda/domain/notice/service/command/dto/CreateNoticeCommand.kt
  src/main/kotlin/com/mjucow/eatda/domain/notice/service/command/dto/UpdateNoticeCommand.kt
  src/main/kotlin/com/mjucow/eatda/domain/notice/service/query/NoticeQueryService.kt
  src/main/kotlin/com/mjucow/eatda/domain/notice/service/query/dto/NoticeDto.kt
  src/main/kotlin/com/mjucow/eatda/domain/notice/service/query/dto/Notices.kt
  src/main/kotlin/com/mjucow/eatda/domain/store/entity/Category.kt
  src/main/kotlin/com/mjucow/eatda/persistence/notice/NoticeRepository.kt
  src/main/kotlin/com/mjucow/eatda/presentation/notice/NoticeController.kt
  src/main/kotlin/com/mjucow/eatda/presentation/store/category/CategoryController.kt
  src/main/resources/application.yml
  src/main/resources/db/changelog/230925-init.sql
  src/main/resources/db/changelog/231004-notioce.sql
  src/test/kotlin/com/mjucow/eatda/domain/notice/entity/NoticeTest.kt
  src/test/kotlin/com/mjucow/eatda/domain/notice/entity/objectmother/NoticeMother.kt
  src/test/kotlin/com/mjucow/eatda/domain/notice/service/command/NoticeCommandServiceTest.kt
  src/test/kotlin/com/mjucow/eatda/domain/notice/service/query/NoticeQueryServiceTest.kt
  src/test/kotlin/com/mjucow/eatda/domain/store/entity/objectmother/EntityMother.kt
  src/test/kotlin/com/mjucow/eatda/domain/store/entity/objectmother/ObjectMother.kt
  src/test/kotlin/com/mjucow/eatda/presentation/notice/NoticeMvcTest.kt
  src/test/resources/application.yml
Labels: feature, size/XL

#34 [refactor] findByIdOrNull -> getReferenceById
  src/main/kotlin/com/mjucow/eatda/domain/notice/service/command/NoticeCommandService.kt
  src/main/kotlin/com/mjucow/eatda/domain/notice/service/query/NoticeQueryService.kt
  src/main/kotlin/com/mjucow/eatda/domain/store/service/command/CategoryCommandService.kt
  src/main/kotlin/com/mjucow/eatda/domain/store/service/command/StoreCommandService.kt
  src/main/kotlin/com/mjucow/eatda/domain/store/service/query/CategoryQueryService.kt
  src/main/kotlin/com/mjucow/eatda/domain/store/service/query/StoreQueryService.kt
  src/test/kotlin/com/mjucow/eatda/domain/store/service/query/CategoryQueryServiceDataTest.kt
  src/test/kotlin/com/mjucow/eatda/domain/store/service/query/StoreQueryServiceDataTest.kt
Labels: refactor, size/M

#30 [feature] menu application 구현 및 테스트 작성
  src/main/kotlin/com/mjucow/eatda/domain/store/service/command/MenuCommandService.kt
  src/main/kotlin/com/mjucow/eatda/domain/store/service/command/dto/MenuCreateCommand.kt
  src/main/kotlin/com/mjucow/eatda/domain/store/service/command/dto/MenuUpdateCommand.kt
  src/main/kotlin/com/mjucow/eatda/domain/store/service/query/MenuDto.kt
  src/main/kotlin/com/mjucow/eatda/domain/store/service/query/MenuQueryService.kt
  src/main/kotlin/com/mjucow/eatda/domain/store/service/query/dto/MenuList.kt
  src/main/kotlin/com/mjucow/eatda/persistence/store/MenuRepository.kt
  src/test/kotlin/com/mjucow/eatda/domain/store/entity/objectmother/MenuMother.kt
  src/test/kotlin/com/mjucow/eatda/domain/store/service/command/MenuCommandServiceTest.kt
  src/test/kotlin/com/mjucow/eatda/domain/store/service/query/MenuQueryServiceTest.kt
Labels: feature, size/L

#31 [feature] menu api 구현 및 테스트 작성
  src/main/kotlin/com/mjucow/eatda/domain/store/service/command/MenuCommandService.kt
  src/main/kotlin/com/mjucow/eatda/domain/store/service/command/dto/MenuCreateCommand.kt
  src/main/kotlin/com/mjucow/eatda/domain/store/service/command/dto/MenuUpdateCommand.kt
  src/main/kotlin/com/mjucow/eatda/presentation/store/StoreController.kt
  src/main/kotlin/com/mjucow/eatda/presentation/store/menu/MenuController.kt
  src/test/kotlin/com/mjucow/eatda/domain/store/service/command/MenuCommandServiceTest.kt
  src/test/kotlin/com/mjucow/eatda/presentation/store/StoreControllerMvcTest.kt
  src/test/kotlin/com/mjucow/eatda/presentation/store/menu/MenuControllerMvcTest.kt
Labels: feature, size/L

#33 [etc] update open api
  .run/EatdaApplication.run.xml
  src/main/resources/static/swagger-ui/openapi3.yaml
  src/test/kotlin/com/mjucow/eatda/domain/store/service/query/CategoryQueryServiceDataTest.kt
  src/test/kotlin/com/mjucow/eatda/domain/store/service/query/StoreQueryServiceDataTest.kt
  src/test/kotlin/com/mjucow/eatda/presentation/store/StoreControllerMvcTest.kt
  src/test/kotlin/com/mjucow/eatda/presentation/store/category/CategoryMvcTest.kt
  src/test/kotlin/com/mjucow/eatda/presentation/store/menu/MenuControllerMvcTest.kt
Labels: etc, size/L

#35 [etc] 테스트 문구 수정
  src/test/kotlin/com/mjucow/eatda/domain/notice/entity/NoticeTest.kt
  src/test/kotlin/com/mjucow/eatda/domain/notice/service/command/NoticeCommandServiceTest.kt
  src/test/kotlin/com/mjucow/eatda/domain/notice/service/query/NoticeQueryServiceTest.kt
Labels: etc, size/S
