Repository COW-dev/eat-da-be, pull requests merged in 2023-09, with the labels that each got.

#2 [Etc] auto assign 설정 변경
  .github/auto_assign.yml
Labels: 기타, size/XS

#4 [ETA] codecov action 추가
  .github/workflows/codecov.yml
Labels: size/S

#5 [Etc] Project Setup
  build.gradle.kts
  compose.yaml
  gradle.properties
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle.kts
  src/main/kotlin/com/mjucow/eatda/EatdaApplication.kt
  src/main/resources/application.yml
  src/main/resources/logback/logback-local.xml
  src/test/kotlin/com/mjucow/eatda/EatdaApplicationTests.kt
  src/test/resources/application.yml
  src/test/resources/logback-test.xml
Labels: 기타, size/XL

#6 [Etc] Ktlint gradle 설정 및 github action 추가
  .editorconfig
  .github/workflows/ktlint-check.yml
  build.gradle.kts
  settings.gradle.kts
  src/test/kotlin/com/mjucow/eatda/EatdaApplicationTests.kt
Labels: style, size/M

#8 [etc] pr title check and auto labeling github action 추가
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/task-category-auto-labeling.yml
Labels: etc, size/M

#7 [etc] setup ci test github action
  .github/workflows/test.yml
  gradle.properties
Labels: etc, size/S

#9 [etc] kt, kts 파일 마지막 줄 개행하는 걸로 변경
  .editorconfig
Labels: etc, size/XS

#10 [feature] add auditing and create base entity
  src/main/kotlin/com/mjucow/eatda/EatdaApplication.kt
  src/main/kotlin/com/mjucow/eatda/domain/common/BaseEntity.kt
Labels: feature, size/M

#11 [feature] 공통 예외처리 컨트롤러 구현
  .editorconfig
  src/main/kotlin/com/mjucow/eatda/presentation/common/ApiResponse.kt
  src/main/kotlin/com/mjucow/eatda/presentation/common/DomainControllerAdvice.kt
  src/main/kotlin/com/mjucow/eatda/presentation/common/GlobalControllerAdvice.kt
  src/main/kotlin/com/mjucow/eatda/presentation/common/GlobalExceptionHandler.kt
Labels: feature, size/M

#12 [etc] liquibase 적용
  .editorconfig
  .github/workflows/ktlint-check.yml
  build.gradle.kts
  src/main/resources/application.yml
  src/main/resources/db/changelog/230925-init.sql
  src/main/resources/db/changelog/changelog-master.yml
  src/test/kotlin/com/mjucow/eatda/AbstractApplicationTest.kt
  src/test/kotlin/com/mjucow/eatda/EatdaApplicationTests.kt
  src/test/resources/application.yml
Labels: etc, size/L

#13 [feature] category entity 정의
  src/main/kotlin/com/mjucow/eatda/domain/store/category/Category.kt
  src/main/resources/application.yml
Labels: feature, size/S

#14 [style] xml, yaml 들여쓰기 수정
  compose.yaml
  src/main/resources/application.yml
  src/main/resources/db/changelog/changelog-master.yml
  src/main/resources/logback/logback-local.xml
Labels: style, size/M

#15 [etc] restdocs와 openapi3를 이용한 swagger 생성
  .editorconfig
  .run/EatdaApplication.run.xml
  .run/EatdaApplicationKt.run.xml
  .run/eat-da-be [bootRun].run.xml
  build.gradle.kts
  compose.yaml
  gradle.properties
  settings.gradle.kts
  src/main/kotlin/com/mjucow/eatda/EatdaApplication.kt
  src/main/kotlin/com/mjucow/eatda/common/config/JpaAuditingConfiguration.kt
  src/main/kotlin/com/mjucow/eatda/common/config/StaticRoutingConfiguration.kt
  src/main/resources/application.yml
  src/main/resources/static/swagger-ui/favicon-16x16.png
  src/main/resources/static/swagger-ui/favicon-32x32.png
  src/main/resources/static/swagger-ui/index.css
  src/main/resources/static/swagger-ui/openapi3.yaml
  src/main/resources/static/swagger-ui/swagger-initializer.js
  src/main/resources/static/swagger-ui/swagger-ui-bundle.js
  src/main/resources/static/swagger-ui/swagger-ui-bundle.js.map
  src/main/resources/static/swagger-ui/swagger-ui-standalone-preset.js
  src/main/resources/static/swagger-ui/swagger-ui-standalone-preset.js.map
  src/main/resources/static/swagger-ui/swagger-ui.css
  src/main/resources/static/swagger-ui/swagger-ui.css.map
  src/main/resources/static/swagger-ui/swagger-ui.html
  src/test/kotlin/com/mjucow/eatda/AbstractMockMvcTest.kt
Labels: etc, size/L

#19 [etc] springmockk 의존성 추가 및 mockito-core 제외
  build.gradle.kts
  gradle.properties
  src/test/resources/application.yml
Labels: etc, size/XS

#21 [etc] codecov 불필요한 동작 제거
  .github/workflows/codecov.yml
Labels: etc, size/XS

#18 [feature] Category Domain 정의 및 CRUD 개발
  build.gradle.kts
  gradle.properties
  src/main/kotlin/com/mjucow/eatda/domain/common/BaseEntity.kt
  src/main/kotlin/com/mjucow/eatda/domain/store/category/Category.kt
  src/main/kotlin/com/mjucow/eatda/domain/store/entity/Category.kt
  src/main/kotlin/com/mjucow/eatda/domain/store/service/command/CategoryCommandService.kt
  src/main/kotlin/com/mjucow/eatda/domain/store/service/command/dto/CreateCommand.kt
  src/main/kotlin/com/mjucow/eatda/domain/store/service/command/dto/UpdateNameCommand.kt
  src/main/kotlin/com/mjucow/eatda/domain/store/service/query/CategoryQueryService.kt
  src/main/kotlin/com/mjucow/eatda/domain/store/service/query/dto/Categories.kt
  src/main/kotlin/com/mjucow/eatda/domain/store/service/query/dto/CategoryDto.kt
  src/main/kotlin/com/mjucow/eatda/persistence/store/CategoryRepository.kt
  src/main/kotlin/com/mjucow/eatda/presentation/store/category/CategoryController.kt
  src/main/resources/db/changelog/230925-init.sql
  src/test/kotlin/com/mjucow/eatda/domain/AbstractDataTest.kt
  src/test/kotlin/com/mjucow/eatda/domain/store/service/command/CategoryCommandServiceDataTest.kt
  src/test/kotlin/com/mjucow/eatda/domain/store/service/query/CategoryQueryServiceDataTest.kt
  src/test/kotlin/com/mjucow/eatda/presentation/AbstractMockMvcTest.kt
  src/test/kotlin/com/mjucow/eatda/presentation/store/category/CategoryMvcTest.kt
  src/test/resources/application.yml
Labels: feature, size/XL

#22 [etc] codecov 설정 파일 추가
  codecov.yml
Labels: etc, size/XS

#20 [etc] timezone 제거 및 Instant 사용
  compose.yaml
  src/main/kotlin/com/mjucow/eatda/common/config/JacksonConfiguration.kt
  src/main/kotlin/com/mjucow/eatda/domain/common/BaseEntity.kt
Labels: etc, size/M

#23 [etc] jacoco 설정 및 테스트 수정
  .github/workflows/codecov.yml
  .github/workflows/test.yml
  build.gradle.kts
  gradle.properties
  src/main/kotlin/com/mjucow/eatda/domain/store/service/command/CategoryCommandService.kt
  src/test/kotlin/com/mjucow/eatda/domain/store/service/command/CategoryCommandServiceDataTest.kt
Labels: etc, size/L

#24 [feature] store 도메인 정의 및 sql 추가 및 test 작성
  codecov.yml
  gradle.properties
  src/main/kotlin/com/mjucow/eatda/common/vo/PhoneNumber.kt
  src/main/kotlin/com/mjucow/eatda/common/vo/Point.kt
  src/main/kotlin/com/mjucow/eatda/domain/store/entity/Store.kt
  src/main/resources/application.yml
  src/main/resources/db/changelog-master.yml
  src/main/resources/db/changelog/230929-store.sql
  src/main/resources/db/changelog/changelog-master.yml
  src/test/kotlin/com/mjucow/eatda/common/vo/PhoneNumberTest.kt
  src/test/kotlin/com/mjucow/eatda/common/vo/VOTest.kt
  src/test/kotlin/com/mjucow/eatda/domain/store/entity/CategoryTest.kt
  src/test/kotlin/com/mjucow/eatda/domain/store/entity/StoreTest.kt
  src/test/kotlin/com/mjucow/eatda/domain/store/entity/objectmother/ObjectMother.kt
  src/test/kotlin/com/mjucow/eatda/domain/store/entity/objectmother/StoreMother.kt
  src/test/kotlin/com/mjucow/eatda/domain/store/service/command/CategoryCommandServiceDataTest.kt
  src/test/resources/application.yml
Labels: feature, size/XL
