Repository COW-dev/eat-da-be, pull requests merged in 2023-11, with the labels that each got.

#36 [feature] banner 도메인 구현 및 테스트 코드 작성
  src/main/kotlin/com/mjucow/eatda/domain/banner/entity/Banner.kt
  src/main/resources/db/changelog/231004-notice.sql
  src/main/resources/db/changelog/231016-banner.sql
  src/main/resources/db/changelog/231105-expired_banner.sql
  src/test/kotlin/com/mjucow/eatda/domain/banner/entity/BannerTest.kt
  src/test/kotlin/com/mjucow/eatda/domain/notice/entity/NoticeTest.kt
Labels: feature, size/L

#37 [etc] add release drafter github action
  .github/workflows/release-drafter-config.yml
  .github/workflows/release-drafter.yml
Labels: etc, size/M

#38 [etc] move config and filter test action
  .github/release-drafter-config.yml
  .github/workflows/test.yml
Labels: etc, size/XS

#40 [etc] change-release-draft-github-action-to-github-app
  .github/release-drafter.yml
  .github/workflows/release-drafter.yml
Labels: etc, size/S

#41 [fix] downgrade postgres version
  compose.yaml
  src/test/kotlin/com/mjucow/eatda/AbstractApplicationTest.kt
  src/test/kotlin/com/mjucow/eatda/domain/AbstractDataTest.kt
Labels: fix, size/XS

#39 [feature] banner application/api 구현 및 테스트 작성
  src/main/kotlin/com/mjucow/eatda/domain/banner/service/command/BannerCommandService.kt
  src/main/kotlin/com/mjucow/eatda/domain/banner/service/command/dto/CreateBannerCommand.kt
  src/main/kotlin/com/mjucow/eatda/domain/banner/service/command/dto/UpdateBannerCommand.kt
  src/main/kotlin/com/mjucow/eatda/domain/banner/service/query/BannerQueryService.kt
  src/main/kotlin/com/mjucow/eatda/domain/banner/service/query/dto/BannerDto.kt
  src/main/kotlin/com/mjucow/eatda/domain/banner/service/query/dto/Banners.kt
  src/main/kotlin/com/mjucow/eatda/domain/notice/service/command/NoticeCommandService.kt
  src/main/kotlin/com/mjucow/eatda/persistence/banner/BannerRepository.kt
  src/main/kotlin/com/mjucow/eatda/presentation/banner/BannerController.kt
  src/main/kotlin/com/mjucow/eatda/presentation/notice/NoticeController.kt
  src/test/kotlin/com/mjucow/eatda/domain/banner/entity/BannerTest.kt
  src/test/kotlin/com/mjucow/eatda/domain/banner/entity/objectmother/BannerMother.kt
  src/test/kotlin/com/mjucow/eatda/domain/banner/service/command/BannerCommandServiceTest.kt
  src/test/kotlin/com/mjucow/eatda/domain/banner/service/query/BannerQueryServiceTest.kt
  src/test/kotlin/com/mjucow/eatda/domain/notice/service/command/NoticeCommandServiceTest.kt
  src/test/kotlin/com/mjucow/eatda/domain/store/service/command/CategoryCommandServiceDataTest.kt
  src/test/kotlin/com/mjucow/eatda/presentation/banner/BannerMvcTest.kt
  src/test/kotlin/com/mjucow/eatda/presentation/notice/NoticeMvcTest.kt
Labels: feature, size/XL

#43 [etc] etc tag maintanance로 처리
  .github/release-drafter.yml
Labels: etc, size/XS

#44 v.0.1.0-Release
  .github/release-drafter.yml
  .github/workflows/deploy.yml
  Dockerfile
  build.gradle.kts
  compose.yaml
  gradle.properties
  src/main/resources/application.yml
  src/main/resources/logback/logback-prod.xml
Labels: size/L

#45 [etc] fix deploy yml
  .github/workflows/deploy.yml
Labels: etc, size/XS

#46 v.0.1.1-Release
  .github/workflows/deploy.yml
Labels: size/XS

#47 [etc] change aws credential
  .github/workflows/deploy.yml
Labels: etc, size/XS

#48 v0.1.2-Release
  .github/workflows/deploy.yml
Labels: size/XS

#49 [etc] update ssh key
  .github/workflows/deploy.yml
  gradle.properties
Labels: size/XS

#50 v0.1.3-Release
  .github/workflows/deploy.yml
  gradle.properties
Labels: size/XS

#52 [etc] redis set up
  .github/workflows/deploy.yml
  .gitignore
  build.gradle.kts
  compose.yaml
  src/main/kotlin/com/mjucow/eatda/common/config/RedisConfiguration.kt
  src/main/kotlin/com/mjucow/eatda/common/properties/PropertiesConfiguration.kt
  src/main/kotlin/com/mjucow/eatda/common/properties/RedisProperties.kt
  src/main/resources/application.yml
  src/test/kotlin/com/mjucow/eatda/domain/AbstractCacheTest.kt
  src/test/resources/application.yml
Labels: etc, size/L

#53 [etc] fix deploy command
  .github/workflows/deploy.yml
Labels: etc, size/XS

#54 [feature] popular store
  build.gradle.kts
  src/main/kotlin/com/mjucow/eatda/common/config/RedisConfiguration.kt
  src/main/kotlin/com/mjucow/eatda/domain/poplarstore/entity/PopularStore.kt
  src/main/kotlin/com/mjucow/eatda/domain/poplarstore/service/PopularStoreCacheService.kt
  src/main/kotlin/com/mjucow/eatda/domain/poplarstore/service/PopularStoreCommandService.kt
  src/main/kotlin/com/mjucow/eatda/domain/poplarstore/service/PopularStoreQueryService.kt
  src/main/kotlin/com/mjucow/eatda/domain/poplarstore/service/dto/PopularStoreDto.kt
  src/main/kotlin/com/mjucow/eatda/domain/poplarstore/service/dto/PopularStoreDtos.kt
  src/main/kotlin/com/mjucow/eatda/domain/store/service/query/StoreQueryService.kt
  src/main/kotlin/com/mjucow/eatda/presentation/store/popularstore/PopularStoreController.kt
  src/test/kotlin/com/mjucow/eatda/domain/AbstractCacheTest.kt
  src/test/kotlin/com/mjucow/eatda/domain/poplarstore/service/PopularStoreCacheServiceTest.kt
  src/test/kotlin/com/mjucow/eatda/domain/poplarstore/service/PopularStoreCommandServiceTest.kt
  src/test/kotlin/com/mjucow/eatda/domain/poplarstore/service/PopularStoreQueryServiceTest.kt
  src/test/kotlin/com/mjucow/eatda/domain/store/service/query/StoreQueryServiceDataTest.kt
  src/test/kotlin/com/mjucow/eatda/presentation/store/popularstore/PopularStoreControllerTest.kt
  src/test/resources/application.yml
Labels: feature, size/XL

#55 [fix] swagger tag
  .github/workflows/deploy.yml
  src/main/resources/static/swagger-ui/openapi3.yaml
  src/test/kotlin/com/mjucow/eatda/presentation/banner/BannerMvcTest.kt
  src/test/kotlin/com/mjucow/eatda/presentation/store/StoreControllerMvcTest.kt
Labels: fix, size/L

#57 v0.1.4-Release
  .github/workflows/deploy.yml
  .gitignore
  build.gradle.kts
  compose.yaml
  src/main/kotlin/com/mjucow/eatda/common/config/RedisConfiguration.kt
  src/main/kotlin/com/mjucow/eatda/common/properties/PropertiesConfiguration.kt
  src/main/kotlin/com/mjucow/eatda/common/properties/RedisProperties.kt
  src/main/kotlin/com/mjucow/eatda/domain/poplarstore/entity/PopularStore.kt
  src/main/kotlin/com/mjucow/eatda/domain/poplarstore/service/PopularStoreCacheService.kt
  src/main/kotlin/com/mjucow/eatda/domain/poplarstore/service/PopularStoreCommandService.kt
  src/main/kotlin/com/mjucow/eatda/domain/poplarstore/service/PopularStoreQueryService.kt
  src/main/kotlin/com/mjucow/eatda/domain/poplarstore/service/dto/PopularStoreDto.kt
  src/main/kotlin/com/mjucow/eatda/domain/poplarstore/service/dto/PopularStoreDtos.kt
  src/main/kotlin/com/mjucow/eatda/domain/store/service/query/StoreQueryService.kt
  src/main/kotlin/com/mjucow/eatda/presentation/store/popularstore/PopularStoreController.kt
  src/main/resources/application.yml
  src/main/resources/static/swagger-ui/openapi3.yaml
  src/test/kotlin/com/mjucow/eatda/domain/AbstractCacheTest.kt
  src/test/kotlin/com/mjucow/eatda/domain/poplarstore/service/PopularStoreCacheServiceTest.kt
  src/test/kotlin/com/mjucow/eatda/domain/poplarstore/service/PopularStoreCommandServiceTest.kt
  src/test/kotlin/com/mjucow/eatda/domain/poplarstore/service/PopularStoreQueryServiceTest.kt
  src/test/kotlin/com/mjucow/eatda/domain/store/service/query/StoreQueryServiceDataTest.kt
  src/test/kotlin/com/mjucow/eatda/presentation/banner/BannerMvcTest.kt
  src/test/kotlin/com/mjucow/eatda/presentation/store/StoreControllerMvcTest.kt
  src/test/kotlin/com/mjucow/eatda/presentation/store/popularstore/PopularStoreControllerTest.kt
  src/test/resources/application.yml
Labels: size/XL

#58 [etc] build with gradle command
  .github/workflows/deploy.yml
Labels: size/XS

#59 [etc] build with gradle command (#58)
  .github/workflows/deploy.yml
Labels: size/XS

#60 [fix] store cache call
  .github/workflows/deploy.yml
  src/main/kotlin/com/mjucow/eatda/domain/store/service/query/StoreQueryService.kt
  src/main/resources/application.yml
Labels: fix, size/XS

#61 Merge pull request #57 from COW-dev/main
  .github/workflows/deploy.yml
  src/main/kotlin/com/mjucow/eatda/domain/store/service/query/StoreQueryService.kt
  src/main/resources/application.yml
Labels: size/XS

#62 [etc] add port in config
  src/main/resources/application.yml
Labels: size/XS

#63 Merge pull request #57 from COW-dev/main
  src/main/resources/application.yml
Labels: size/XS

#64 [refactor] remove postgreqsql test container
  src/test/kotlin/com/mjucow/eatda/AbstractApplicationTest.kt
  src/test/kotlin/com/mjucow/eatda/AbstractSpringContextTest.kt
  src/test/kotlin/com/mjucow/eatda/domain/AbstractCacheTest.kt
  src/test/kotlin/com/mjucow/eatda/domain/AbstractDataTest.kt
  src/test/resources/application.yml
Labels: refactor, size/M

#65 [etc] cors 설정
  build.gradle.kts
  src/main/kotlin/com/mjucow/eatda/common/config/WebConfig.kt
Labels: etc, size/M

#66 v0.1.5-Release
  build.gradle.kts
  gradle.properties
  src/main/kotlin/com/mjucow/eatda/common/config/WebConfig.kt
  src/test/kotlin/com/mjucow/eatda/AbstractApplicationTest.kt
  src/test/kotlin/com/mjucow/eatda/AbstractSpringContextTest.kt
  src/test/kotlin/com/mjucow/eatda/domain/AbstractCacheTest.kt
  src/test/kotlin/com/mjucow/eatda/domain/AbstractDataTest.kt
  src/test/resources/application.yml
Labels: size/M

#68 [feature] expired banner migration job 구현
  src/main/kotlin/com/mjucow/eatda/scheduled/ExpiredBannerBatchJob.kt
  src/main/kotlin/com/mjucow/eatda/scheduled/ScheduleJobConfig.kt
  src/main/resources/application.yml
  src/test/kotlin/com/mjucow/eatda/scheduled/ExpiredBannerBatchJobTest.kt
Labels: feature, size/L
