Repository COW-dev/eat-da-be, pull requests merged in 2023-12, with the labels that each got.

#70 v0.1.6-Release
  src/main/kotlin/com/mjucow/eatda/scheduled/ExpiredBannerBatchJob.kt
  src/main/kotlin/com/mjucow/eatda/scheduled/ScheduleJobConfig.kt
  src/main/resources/application.yml
  src/test/kotlin/com/mjucow/eatda/scheduled/ExpiredBannerBatchJobTest.kt
Labels: size/L

#71 [etc] logger 추가 및 Exception logging 추가
  build.gradle.kts
  src/main/kotlin/com/mjucow/eatda/common/Common.kt
  src/main/kotlin/com/mjucow/eatda/presentation/common/GlobalExceptionHandler.kt
Labels: etc, size/S

#72 [etc] CODEOWNERS 수정
  .github/CODEOWNERS
Labels: etc, size/XS

#73 [etc]Spring boot version 3.1.2 -> 3.1.6
  gradle.properties
Labels: etc, size/XS

#74 [refactor]cursor 기반 page 타입 변경
  src/main/kotlin/com/mjucow/eatda/common/dto/CursorPage.kt
  src/main/kotlin/com/mjucow/eatda/domain/store/service/query/StoreQueryService.kt
  src/main/kotlin/com/mjucow/eatda/persistence/store/StoreCustomRepository.kt
  src/main/kotlin/com/mjucow/eatda/persistence/store/StoreCustomRepositoryImpl.kt
  src/main/kotlin/com/mjucow/eatda/presentation/store/StoreController.kt
  src/test/kotlin/com/mjucow/eatda/domain/store/service/query/StoreQueryServiceDataTest.kt
  src/test/kotlin/com/mjucow/eatda/persistence/store/StoreCustomRepositoryImplTest.kt
  src/test/kotlin/com/mjucow/eatda/presentation/store/StoreControllerMvcTest.kt
Labels: refactor, size/L
