Repository COW-dev/eat-da-be, pull requests merged in 2024-01, with the labels that each got.

#75 [refactor] Swagger UI 라이브러리 변경: Spring REST docs -> Springdoc
  build.gradle.kts
  src/main/kotlin/com/mjucow/eatda/common/config/StaticRoutingConfiguration.kt
  src/main/kotlin/com/mjucow/eatda/common/config/SwaggerConfig.kt
  src/main/kotlin/com/mjucow/eatda/common/vo/PhoneNumber.kt
  src/main/kotlin/com/mjucow/eatda/common/vo/Point.kt
  src/main/kotlin/com/mjucow/eatda/domain/banner/service/command/dto/CreateBannerCommand.kt
  src/main/kotlin/com/mjucow/eatda/domain/banner/service/command/dto/UpdateBannerCommand.kt
  src/main/kotlin/com/mjucow/eatda/domain/banner/service/query/dto/BannerDto.kt
  src/main/kotlin/com/mjucow/eatda/domain/notice/service/command/dto/UpdateNoticeCommand.kt
  src/main/kotlin/com/mjucow/eatda/domain/notice/service/query/dto/NoticeDto.kt
  src/main/kotlin/com/mjucow/eatda/domain/poplarstore/service/dto/PopularStoreDto.kt
  src/main/kotlin/com/mjucow/eatda/domain/store/service/command/dto/CreateCommand.kt
  src/main/kotlin/com/mjucow/eatda/domain/store/service/command/dto/MenuCreateCommand.kt
  src/main/kotlin/com/mjucow/eatda/domain/store/service/command/dto/MenuUpdateCommand.kt
  src/main/kotlin/com/mjucow/eatda/domain/store/service/command/dto/StoreCreateCommand.kt
  src/main/kotlin/com/mjucow/eatda/domain/store/service/command/dto/StoreUpdateCommand.kt
  src/main/kotlin/com/mjucow/eatda/domain/store/service/command/dto/UpdateNameCommand.kt
  src/main/kotlin/com/mjucow/eatda/domain/store/service/query/MenuDto.kt
  src/main/kotlin/com/mjucow/eatda/domain/store/service/query/dto/CategoryDto.kt
  src/main/kotlin/com/mjucow/eatda/domain/store/service/query/dto/StoreDetailDto.kt
  src/main/kotlin/com/mjucow/eatda/presentation/banner/BannerApiPresentation.kt
  src/main/kotlin/com/mjucow/eatda/presentation/banner/BannerController.kt
  src/main/kotlin/com/mjucow/eatda/presentation/common/example/StoreDtosApiResponse.kt
  src/main/kotlin/com/mjucow/eatda/presentation/notice/NoticeApiPresentation.kt
  src/main/kotlin/com/mjucow/eatda/presentation/notice/NoticeController.kt
  src/main/kotlin/com/mjucow/eatda/presentation/store/StoreApiPresentation.kt
  src/main/kotlin/com/mjucow/eatda/presentation/store/StoreController.kt
  src/main/kotlin/com/mjucow/eatda/presentation/store/category/CategoryApiPresentation.kt
  src/main/kotlin/com/mjucow/eatda/presentation/store/category/CategoryController.kt
  src/main/kotlin/com/mjucow/eatda/presentation/store/menu/MenuApiPresentation.kt
  src/main/kotlin/com/mjucow/eatda/presentation/store/menu/MenuController.kt
  src/main/kotlin/com/mjucow/eatda/presentation/store/popularstore/PopularStoreApiPresentation.kt
  src/main/kotlin/com/mjucow/eatda/presentation/store/popularstore/PopularStoreController.kt
  src/main/resources/application.yml
  src/main/resources/static/swagger-ui/favicon-16x16.png
  src/main/resources/static/swagger-ui/favicon-32x32.png
  src/main/resources/static/swagger-ui/index.css
  src/main/resources/static/swagger-ui/openapi3.yaml
  src/main/resources/static/swagger-ui/swagger-initializer.js
  src/main/resources/static/swagger-ui/swagger-ui-bundle.js
  src/main/resources/static/swagger-ui/swagger-ui-bundle.js.map
  src/main/resources/static/swagger-ui/swagger-ui-standalone-preset.js
  src/main/resources/static/swagger-ui/swagger-ui-standalone-preset.js.map
  src/main/resources/static/swagger-ui/swagger-ui.css
  src/main/resources/static/swagger-ui/swagger-ui.css.map
  src/main/resources/static/swagger-ui/swagger-ui.html
Labels: refactor, size/XXL

#77 [etc] version 수정
  gradle.properties
  src/main/kotlin/com/mjucow/eatda/common/config/SwaggerConfig.kt
Labels: etc, size/XS

#78 v0.1.7-Release
  .github/CODEOWNERS
  build.gradle.kts
  gradle.properties
  src/main/kotlin/com/mjucow/eatda/common/Common.kt
  src/main/kotlin/com/mjucow/eatda/common/config/StaticRoutingConfiguration.kt
  src/main/kotlin/com/mjucow/eatda/common/config/SwaggerConfig.kt
  src/main/kotlin/com/mjucow/eatda/common/dto/CursorPage.kt
  src/main/kotlin/com/mjucow/eatda/common/vo/PhoneNumber.kt
  src/main/kotlin/com/mjucow/eatda/common/vo/Point.kt
  src/main/kotlin/com/mjucow/eatda/domain/banner/service/command/dto/CreateBannerCommand.kt
  src/main/kotlin/com/mjucow/eatda/domain/banner/service/command/dto/UpdateBannerCommand.kt
  src/main/kotlin/com/mjucow/eatda/domain/banner/service/query/dto/BannerDto.kt
  src/main/kotlin/com/mjucow/eatda/domain/notice/service/command/dto/UpdateNoticeCommand.kt
  src/main/kotlin/com/mjucow/eatda/domain/notice/service/query/dto/NoticeDto.kt
  src/main/kotlin/com/mjucow/eatda/domain/poplarstore/service/dto/PopularStoreDto.kt
  src/main/kotlin/com/mjucow/eatda/domain/store/service/command/dto/CreateCommand.kt
  src/main/kotlin/com/mjucow/eatda/domain/store/service/command/dto/MenuCreateCommand.kt
  src/main/kotlin/com/mjucow/eatda/domain/store/service/command/dto/MenuUpdateCommand.kt
  src/main/kotlin/com/mjucow/eatda/domain/store/service/command/dto/StoreCreateCommand.kt
  src/main/kotlin/com/mjucow/eatda/domain/store/service/command/dto/StoreUpdateCommand.kt
  src/main/kotlin/com/mjucow/eatda/domain/store/service/command/dto/UpdateNameCommand.kt
  src/main/kotlin/com/mjucow/eatda/domain/store/service/query/MenuDto.kt
  src/main/kotlin/com/mjucow/eatda/domain/store/service/query/StoreQueryService.kt
  src/main/kotlin/com/mjucow/eatda/domain/store/service/query/dto/CategoryDto.kt
  src/main/kotlin/com/mjucow/eatda/domain/store/service/query/dto/StoreDetailDto.kt
  src/main/kotlin/com/mjucow/eatda/persistence/store/StoreCustomRepository.kt
  src/main/kotlin/com/mjucow/eatda/persistence/store/StoreCustomRepositoryImpl.kt
  src/main/kotlin/com/mjucow/eatda/presentation/banner/BannerApiPresentation.kt
  src/main/kotlin/com/mjucow/eatda/presentation/banner/BannerController.kt
  src/main/kotlin/com/mjucow/eatda/presentation/common/GlobalExceptionHandler.kt
  src/main/kotlin/com/mjucow/eatda/presentation/common/example/StoreDtosApiResponse.kt
  src/main/kotlin/com/mjucow/eatda/presentation/notice/NoticeApiPresentation.kt
  src/main/kotlin/com/mjucow/eatda/presentation/notice/NoticeController.kt
  src/main/kotlin/com/mjucow/eatda/presentation/store/StoreApiPresentation.kt
  src/main/kotlin/com/mjucow/eatda/presentation/store/StoreController.kt
  src/main/kotlin/com/mjucow/eatda/presentation/store/category/CategoryApiPresentation.kt
  src/main/kotlin/com/mjucow/eatda/presentation/store/category/CategoryController.kt
  src/main/kotlin/com/mjucow/eatda/presentation/store/menu/MenuApiPresentation.kt
  src/main/kotlin/com/mjucow/eatda/presentation/store/menu/MenuController.kt
  src/main/kotlin/com/mjucow/eatda/presentation/store/popularstore/PopularStoreApiPresentation.kt
  src/main/kotlin/com/mjucow/eatda/presentation/store/popularstore/PopularStoreController.kt
  src/main/resources/application.yml
  src/main/resources/static/swagger-ui/favicon-16x16.png
  src/main/resources/static/swagger-ui/favicon-32x32.png
  src/main/resources/static/swagger-ui/index.css
  src/main/resources/static/swagger-ui/openapi3.yaml
  src/main/resources/static/swagger-ui/swagger-initializer.js
  src/main/resources/static/swagger-ui/swagger-ui-bundle.js
  src/main/resources/static/swagger-ui/swagger-ui-bundle.js.map
  src/main/resources/static/swagger-ui/swagger-ui-standalone-preset.js
  src/main/resources/static/swagger-ui/swagger-ui-standalone-preset.js.map
  src/main/resources/static/swagger-ui/swagger-ui.css
  src/main/resources/static/swagger-ui/swagger-ui.css.map
  src/main/resources/static/swagger-ui/swagger-ui.html
  src/test/kotlin/com/mjucow/eatda/domain/store/service/query/StoreQueryServiceDataTest.kt
  src/test/kotlin/com/mjucow/eatda/persistence/store/StoreCustomRepositoryImplTest.kt
  src/test/kotlin/com/mjucow/eatda/presentation/store/StoreControllerMvcTest.kt
Labels: size/XXL

#79 [etc] storeId → cursor 수정
  src/main/kotlin/com/mjucow/eatda/domain/store/service/query/StoreQueryService.kt
  src/main/kotlin/com/mjucow/eatda/presentation/store/StoreApiPresentation.kt
  src/main/kotlin/com/mjucow/eatda/presentation/store/StoreController.kt
  src/test/kotlin/com/mjucow/eatda/domain/store/service/query/StoreQueryServiceDataTest.kt
  src/test/kotlin/com/mjucow/eatda/presentation/store/StoreControllerMvcTest.kt
Labels: etc, size/M

#80 [etc] version 수정
  gradle.properties
  src/main/kotlin/com/mjucow/eatda/common/config/SwaggerConfig.kt
Labels: etc, size/XS

#82 v0.1.8-Release
  gradle.properties
  src/main/kotlin/com/mjucow/eatda/common/config/SwaggerConfig.kt
  src/main/kotlin/com/mjucow/eatda/domain/store/service/query/StoreQueryService.kt
  src/main/kotlin/com/mjucow/eatda/presentation/store/StoreApiPresentation.kt
  src/main/kotlin/com/mjucow/eatda/presentation/store/StoreController.kt
  src/test/kotlin/com/mjucow/eatda/domain/store/service/query/StoreQueryServiceDataTest.kt
  src/test/kotlin/com/mjucow/eatda/presentation/store/StoreControllerMvcTest.kt
Labels: size/M

#83 [etc] swagger 수정
  src/main/kotlin/com/mjucow/eatda/domain/notice/service/command/dto/CreateNoticeCommand.kt
  src/main/kotlin/com/mjucow/eatda/domain/store/service/command/dto/CreateCommand.kt
  src/main/kotlin/com/mjucow/eatda/domain/store/service/command/dto/StoreUpdateCommand.kt
Labels: etc, size/XS

#85 [fix] redis 분리 및 api 추가
  .run/EatdaApplication.run.xml
  build.gradle.kts
  src/main/kotlin/com/mjucow/eatda/domain/store/service/query/StoreQueryService.kt
  src/main/kotlin/com/mjucow/eatda/presentation/store/popularstore/PopularStoreController.kt
  src/test/kotlin/com/mjucow/eatda/presentation/store/popularstore/PopularStoreControllerTest.kt
Labels: fix, size/M

#76 [refactor] (Point,PhoneNumber)primitive value -> VO Class
  src/main/kotlin/com/mjucow/eatda/common/vo/Latitude.kt
  src/main/kotlin/com/mjucow/eatda/common/vo/Longitude.kt
  src/main/kotlin/com/mjucow/eatda/common/vo/Point.kt
  src/test/kotlin/com/mjucow/eatda/common/vo/LatitudeTest.kt
  src/test/kotlin/com/mjucow/eatda/common/vo/LongitudeTest.kt
  src/test/kotlin/com/mjucow/eatda/common/vo/PhoneNumberTest.kt
  src/test/kotlin/com/mjucow/eatda/domain/store/entity/objectmother/StoreMother.kt
Labels: refactor, size/L

#87 [etc] Store custom example 삭제
  src/main/kotlin/com/mjucow/eatda/domain/store/service/query/dto/StoreDto.kt
  src/main/kotlin/com/mjucow/eatda/presentation/common/example/StoreDtosApiResponse.kt
  src/main/kotlin/com/mjucow/eatda/presentation/store/StoreApiPresentation.kt
Labels: etc, size/M

#88 [feature] 큐레이션 API 구현
  src/main/kotlin/com/mjucow/eatda/domain/curation/entity/Curation.kt
  src/main/kotlin/com/mjucow/eatda/domain/curation/service/command/CurationCommandService.kt
  src/main/kotlin/com/mjucow/eatda/domain/curation/service/command/dto/AddStoreCommand.kt
  src/main/kotlin/com/mjucow/eatda/domain/curation/service/command/dto/CreateCurationCommand.kt
  src/main/kotlin/com/mjucow/eatda/domain/curation/service/command/dto/UpdateCurationCommand.kt
  src/main/kotlin/com/mjucow/eatda/domain/curation/service/query/CurationQueryService.kt
  src/main/kotlin/com/mjucow/eatda/domain/curation/service/query/dto/CurationDto.kt
  src/main/kotlin/com/mjucow/eatda/domain/curation/service/query/dto/Curations.kt
  src/main/kotlin/com/mjucow/eatda/domain/store/service/query/dto/Stores.kt
  src/main/kotlin/com/mjucow/eatda/persistence/curation/CurationRepository.kt
  src/main/kotlin/com/mjucow/eatda/presentation/curation/CurationApiPresentation.kt
  src/main/kotlin/com/mjucow/eatda/presentation/curation/CurationController.kt
  src/main/resources/db/changelog/231105-expired_banner.sql
  src/main/resources/db/changelog/240129-curation.sql
  src/test/kotlin/com/mjucow/eatda/domain/banner/service/query/BannerQueryServiceTest.kt
  src/test/kotlin/com/mjucow/eatda/domain/curation/entity/CurationTest.kt
  src/test/kotlin/com/mjucow/eatda/domain/curation/entity/objectmother/CurationMother.kt
  src/test/kotlin/com/mjucow/eatda/domain/curation/service/command/CurationCommandServiceTest.kt
  src/test/kotlin/com/mjucow/eatda/domain/curation/service/query/CurationQueryServiceTest.kt
  src/test/kotlin/com/mjucow/eatda/domain/store/entity/StoreTest.kt
  src/test/kotlin/com/mjucow/eatda/domain/store/service/command/MenuCommandServiceTest.kt
  src/test/kotlin/com/mjucow/eatda/presentation/banner/BannerMvcTest.kt
  src/test/kotlin/com/mjucow/eatda/presentation/curation/CurationMvcTest.kt
  src/test/kotlin/com/mjucow/eatda/presentation/notice/NoticeMvcTest.kt
Labels: feature, size/XL
