Repository COW-dev/eat-da-be, pull requests merged in 2024-03, with the labels that each got.

#89 [refactor] 큐레이션 도메인 수정 및 API 추가
  src/main/kotlin/com/mjucow/eatda/domain/curation/entity/Curation.kt
  src/main/kotlin/com/mjucow/eatda/domain/curation/service/command/CurationCommandService.kt
  src/main/kotlin/com/mjucow/eatda/domain/curation/service/command/dto/CreateCurationCommand.kt
  src/main/kotlin/com/mjucow/eatda/domain/curation/service/command/dto/UpdateCurationCommand.kt
  src/main/kotlin/com/mjucow/eatda/domain/curation/service/query/dto/CurationDto.kt
  src/main/kotlin/com/mjucow/eatda/domain/store/service/query/StoreQueryService.kt
  src/main/kotlin/com/mjucow/eatda/persistence/store/StoreCustomRepository.kt
  src/main/kotlin/com/mjucow/eatda/persistence/store/StoreCustomRepositoryImpl.kt
  src/main/kotlin/com/mjucow/eatda/presentation/curation/CurationApiPresentation.kt
  src/main/kotlin/com/mjucow/eatda/presentation/curation/CurationController.kt
  src/main/resources/db/changelog/240214-curation_add_column.sql
  src/test/kotlin/com/mjucow/eatda/domain/curation/entity/CurationTest.kt
  src/test/kotlin/com/mjucow/eatda/domain/curation/entity/objectmother/CurationMother.kt
  src/test/kotlin/com/mjucow/eatda/domain/curation/service/command/CurationCommandServiceTest.kt
  src/test/kotlin/com/mjucow/eatda/domain/store/service/query/StoreQueryServiceDataTest.kt
  src/test/kotlin/com/mjucow/eatda/persistence/store/StoreCustomRepositoryImplTest.kt
  src/test/kotlin/com/mjucow/eatda/presentation/curation/CurationMvcTest.kt
Labels: refactor, size/L

#90 [etc] health check controller 추가
  src/main/kotlin/com/mjucow/eatda/health/HealthCheckController.kt
Labels: etc, size/S

#91 r2m
  src/test/kotlin/com/mjucow/eatda/domain/store/service/query/StoreQueryServiceDataTest.kt
Labels: size/S

#93 [fix] test ignore and ktlint
  build.gradle.kts
  src/main/kotlin/com/mjucow/eatda/health/HealthCheckController.kt
Labels: size/XS

#95 [fix] 배포 스크립트 s3 인자 추가
  .github/workflows/deploy.yml
Labels: fix, size/XS

#98 v0.1.13
  .github/workflows/deploy.yml
  Dockerfile
  gradle.properties
  src/main/kotlin/com/mjucow/eatda/common/config/SwaggerConfig.kt
  src/main/resources/application.yml
Labels: size/S
